// Single source of truth for enums/status strings shared across the app.
// Import from here instead of hardcoding strings in components or API routes.

export const USER_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  BANNED: "BANNED",
  DELETED: "DELETED",
} as const;

export const PROFILE_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
  BANNED: "BANNED",
} as const;

export const PAYMENT_STATUS = {
  PENDING_REVIEW: "PENDING_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  NEEDS_INFO: "NEEDS_INFO",
} as const;

export const SUBSCRIPTION_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
} as const;

export const REPORT_STATUS = {
  OPEN: "OPEN",
  UNDER_REVIEW: "UNDER_REVIEW",
  RESOLVED: "RESOLVED",
  DISMISSED: "DISMISSED",
} as const;

export const ROLES = {
  USER: "USER",
  MODERATOR: "MODERATOR",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
} as const;

export const MIN_AGE = 18;

// Notification types — extend here, reference by key everywhere else.
export const NOTIFICATION_TYPES = {
  NEW_LIKE: "NEW_LIKE",
  NEW_MATCH: "NEW_MATCH",
  NEW_MESSAGE: "NEW_MESSAGE",
  CONNECTION_REQUEST: "CONNECTION_REQUEST",
  CONNECTION_ACCEPTED: "CONNECTION_ACCEPTED",
  NEW_FOLLOWER: "NEW_FOLLOWER",
  POST_LIKE: "POST_LIKE",
  COMMENT: "COMMENT",
  PROFILE_APPROVED: "PROFILE_APPROVED",
  PROFILE_REJECTED: "PROFILE_REJECTED",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  PAYMENT_APPROVED: "PAYMENT_APPROVED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  MEMBERSHIP_EXPIRING: "MEMBERSHIP_EXPIRING",
  MEMBERSHIP_ACTIVATED: "MEMBERSHIP_ACTIVATED",
  ADMIN_ANNOUNCEMENT: "ADMIN_ANNOUNCEMENT",
} as const;
